name: Deploy Bot

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.8'

      - name: Install caprover
        run: sudo npm install -g caprover

      - name: Create tar
        run: tar -cvf ./deploy.tar --exclude='*.map' ecosystem.config.js captain-definition package.json package-lock.json yarn.lock Dockerfile bot.mjs bank.txt

      - name: Deploy
        run: caprover deploy -h ${{ secrets.CAPROVER_SERVER_PROD }} -p ${{ secrets.CAPROVER_PASSWORD_PROD }} -a aghroum -t ./deploy.tar